name = "Femrot"
author = "Tazer & Rowan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8814f595fd08767a228e8597521a0ce1ae1182d03b86157070f4d867528f502"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
