name = "Femrot"
author = "Tazer & Rowan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a17b299b1e2d432f5a42158d14424df7dbaa32c77e402f857c213bbffb55899e"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
