name = "Femrot"
author = "Tazer & Rowan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69b2bbc21cdeb729e6a14d935ee4ea691ae6087a6edf1b27c93a7c721c4f698a"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
