name = "Femrot"
author = "Tazer & Rowan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56a1c125b9ab1caa72d9ed7882bec6d034c2b99e23e8abc4af56528324799b98"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
