// TO REMOVE ITEMS FROM EMI/JEI/REI AND CREATIVE TAB
import { badItemList } from '../constants'
JEIEvents.hideItems(event => {
    event.hide([
      'crimson_stem',
      'stripped_crimson_stem',
      'crimson_hyphae',
      'stripped_crimson_hyphae',
      'crimson_planks',
      'crimson_stairs',
      'crimson_slab',
      'crimson_fence',
      'crimson_fence_gate',
      'crimson_door',
      'crimson_trapdoor',
      'crimson_pressure_plate',
      'crimson_button',
      'nomansland:trimmed_crimson_planks',
      'crimson_nylium',
      'crimson_fungus',
      'crimson_roots',
      'crimson_sign',
      'crimson_hanging_sign',
      'supplementaries:sign_post_crimson',
      'suppsquared:item_shelf_crimson',
      'nomansland:crimson_bookshelf',
      'farmersdelight:crimson_cabinet',
      'create:crimson_window',
      'create:crimson_window_pane',
    
      'warped_stem',
      'stripped_warped_stem',
      'warped_hyphae',
      'stripped_warped_hyphae',
      'warped_planks',
      'warped_stairs',
      'warped_slab',
      'warped_fence',
      'warped_fence_gate',
      'warped_door',
      'warped_trapdoor',
      'warped_pressure_plate',
      'warped_button',
      'nomansland:trimmed_warped_planks',
      'warped_nylium',
      'warped_fungus',
      'warped_roots',
      'warped_sign',
      'warped_hanging_sign',
      'supplementaries:sign_post_warped',
      'suppsquared:item_shelf_warped',
      'nomansland:warped_bookshelf',
      'farmersdelight:warped_cabinet',
      'create:warped_window',
      'create:warped_window_pane',
    
      'nether_brick',
    
      'netherite_ingot',
    
      'diamond_helmet',
      'diamond_chestplate',
      'diamond_leggings',
      'diamond_boots',

      'supplementaries:rope_arrow',
    ])
})
